apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/codeclubcph/gitops-workshop.git
    targetRevision: main
    path: argocd # This tells Argo to watch the folder containing your other App manifests!
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true